language: node_js
node_js:
    - "6"
cache:
    directories:
        - node_modules
before_install:
    - openssl aes-256-cbc -K $encrypted_bcb0da9ada9b_key -iv $encrypted_bcb0da9ada9b_iv -in ./conf/matchmyroute-backend-firebase-adminsdk-jm5jb-e33eab9419.json.enc -out ./conf/matchmyroute-backend-firebase-adminsdk-jm5jb-e33eab9419.json -d
addons:
    postgresql: 9.6
        apt:
            packages:
                - postgresql-9.6-postgis-2.3
before_script:
    - psql -U postgres -c "create extension postgis"
    - psql -c "CREATE USER testuser WITH PASSWORD 'test' SUPERUSER;"
    - psql -c 'CREATE DATABASE "matchMyRouteTest" WITH OWNER testuser;'
