language: node_js
node_js:
    - "6"
cache:
    directories:
        - node_modules
before_install:
    - openssl aes-256-cbc -K $encrypted_bcb0da9ada9b_key -iv $encrypted_bcb0da9ada9b_iv -in matchmyroute-backend-firebase-adminsdk-jm5jb-e33eab9419.json.enc -out matchmyroute-backend-firebase-adminsdk-jm5jb-e33eab9419.json -d
