language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=staging
  - URL="https://matchmyroute-backend.appspot.com"
  - secure: R4X0jHjUAwiTuTlxa89Gwyfg98UnQcqFo0sKBs+5vTkUHGzOyOvfezFwa9Mht5AmcrFvSDqYPgTrSSzCRsL0A0JV4yaVbPOa/IlDT2t6keLU0KTDiIvr+cT+d0pEYh5oxI0TmXAH9AjYlnhDyP6h199TyWSdUXUQy6YoaQbcC9dK34TZk8pI8q6Up5ltnLBfncWrFtUyXVFrJj8LmC3RHmCxWyGqW4PNZw4JuRk5oTV3/z+sY8M9TievwZtzsgIsOVDSXYIiU2p0p+MDlhxdxt0CaZC6U8wki8Vd3cs1WKwj6k1+fHcJ4BClqQk/2bifiyq/lrqbA29fqcn14BPXECBOHvDZ9djWPqgWAWjCaQF95LOf5E8oAkvgOHtscR2VSzMsSLqJBPu91EbHzvvhXwKgt00ivhJUeYj1FMpylBaGS8iaVnPHzVuZkVRshamW+WDaW7csHwJG6/slKKJpSBnUnRRpAfK8j7yObNrqrmMMtBDwdxVRuVNnSoA/hvVe0ZIHpJjc+PWnLUTubcepmn4WIVFfgp768hv6z0CGPT7/u93DQ2loMjFOwXkuHo3VX9yiHaNxoCPcGrX80oPX2GazvE2dnyu9h/1DlRJTOLciMH/3Im5euj5vXmQI7pi9ufcOS3eQIkEmK0Wb4hjGGvJRRzHQWUkT7M+FTO+qai4=
before_install:
- openssl aes-256-cbc -K $encrypted_6b1d22c161fd_key -iv $encrypted_6b1d22c161fd_iv
  -in ./conf/key-file.json.enc -out ./conf/key-file.json -d
- openssl aes-256-cbc -K $encrypted_bcb0da9ada9b_key -iv $encrypted_bcb0da9ada9b_iv
  -in ./conf/matchmyroute-backend-firebase-adminsdk-jm5jb-e33eab9419.json.enc -out
  ./conf/matchmyroute-backend-firebase-adminsdk-jm5jb-e33eab9419.json -d
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
- psql -U postgres -c "create extension postgis"
- psql -c "CREATE USER testuser WITH PASSWORD 'test' SUPERUSER;"
- psql -c 'CREATE DATABASE "matchMyRouteTest" WITH OWNER testuser;'
script:
- npm run test
- npm run build
deploy:
  provider: gae
  keyfile: "./conf/key-file.json"
  project: matchmyroute-backend
  config: "./build/app.yaml"
  skip_cleanup: true
after_deploy:
- npm run e2etest
notifications:
  slack:
    secure: TOt8glnjOcUX4kOLQ0sHJhq38Wtmwl1iZM7kbL9931Xa6T8zNkjsPT8phzmovpvEzYvxSzd4w1AymyPGCfpV1qXH5Gxnqw2rdrhcFMZV7jJiFLLHBvXKFjcamS260RKEpSeBz7hK963XD4nkD7YlHIOOebMEgJCr8wxJqgaNFQz90Wgvop/b1GhYp6oI1AeB7CBZYS6RhYcKZsOyuPgCx2YITsxlJt9LKt8Sk7VKxcY+MzJ3nOXl1EIDpkX+TPuRaPH2Z0pFWswoNLMpnrk0uVrBOXqbTKwnNxQulHQy6MefmRx/NHRbWiaehQHmKAP1Pgc8hQImkIWkyNS4TWJ7z23wb5ZY4pg63Ne2LJGGlYBrAL0G7G4nOVrDDcfa/i8NsmZ8Ok93cD9QPk/zYbUhdsfUmLsmn8jESw3K5zbW8OL5XosS3sAucdAwV+yg1eJuEF8DGL/RQI3X68LutR5WalQ6p/LJK8fg2EJshadNNpg2csvo1z1FhHSGJKeax4YMbc5Qrk5VKu72zscEPtSMfZMM+ps/HdoU6LmxPMnWLAfAy9Ms4OIqPGlDO94UGFzGRiY4PSZgRdElAv/Fgr7p8L971vkXOonkiG6j5MI+jWjj1yibvzjcdOW5+ddjfTLmXW+XKa9Oc15Jju5yCFlX5weT+DIffqqePnmTyO4cF3Y=
