import { initialiseSeneca } from "./helper";

// DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!!!!!!

export default function() {
    const services: { [key: string]: any } = {};
    initialiseSeneca(services);
}
